# Generated by Django 5.0.6 on 2024-06-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="lasst_name",
            new_name="last_name",
        ),
    ]
