# Generated by Django 5.0.6 on 2024-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_rename_lasst_name_customer_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
