# Generated by Django 5.0.6 on 2024-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0004_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="is_discounted",
            field=models.BooleanField(default=False),
        ),
    ]
