# Generated by Django 5.0.6 on 2024-06-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0005_products_is_discounted"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
