# Generated by Django 5.0.6 on 2024-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0006_products_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="storage_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
