# Generated by Django 5.0.6 on 2024-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0007_products_storage_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
