# Generated by Django 5.0.6 on 2024-06-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0008_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="shopping.customer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchase",
            name="purchase_date",
            field=models.DateTimeField(),
        ),
    ]
