# Generated by Django 5.0.6 on 2024-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0009_purchase_customer_alter_purchase_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="purchase_date",
            field=models.DateField(),
        ),
    ]
