# Generated by Django 5.0.6 on 2024-06-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0010_alter_purchase_purchase_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("street", models.CharField(max_length=200)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="address",
                        to="shopping.customer",
                    ),
                ),
            ],
        ),
    ]
