# Generated by Django 5.0.6 on 2024-06-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0011_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
    ]
