# Generated by Django 5.0.6 on 2024-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0013_purchaseitem_purchase_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
