# Generated by Django 5.0.6 on 2024-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0014_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
